config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "application#index"

    resources :projects, except: [:index, :show]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:index, :new, :create] do
      member do
        patch :make_default
      end
    end
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show] do
    resources :tickets do
      collection do
        post :upload_file
        get :search
      end

      member do
        patch :watch
      end
    end
  end

  scope path: "tickets/:ticket_id", as: :ticket do
    resources :comments, only: [:create]

    delete "tags/remove/:id", to: "tags#remove", as: :remove_tag
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  belongs_to :author, class_name: "User"
  belongs_to :state, optional: true

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  has_many_attached :attachments

  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags, uniq: true

  has_and_belongs_to_many :watchers, -> { distinct },
    join_table: "ticket_watchers",
    class_name: "User"

  searcher do
    label :tag, from: :tags, field: "name"
    label :state, from: :state, field: "name"
  end

  before_create :assign_default_state

  private

  def assign_default_state
    self.state ||= State.default
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: %i(show edit update destroy watch)

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    if params[:attachments].present?
      @ticket.attachments.attach(params[:attachments])
    end
    @ticket.tags = processed_tags

    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def show
    @comment = @ticket.comments.build(state: @ticket.state)
    @states = State.all
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      if params[:attachments].present?
        @ticket.attachments.attach(params[:attachments])
      end
      @ticket.tags << processed_tags
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."

    redirect_to @project
  end

  def watch
    if @ticket.watchers.exists?(current_user.id)
      @ticket.watchers.destroy(current_user)
      flash[:notice] = "You are no longer watching this ticket."
    else
      @ticket.watchers << current_user
      flash[:notice] = "You are now watching this ticket."
    end

    redirect_to project_ticket_path(@ticket.project, @ticket)
  end

  def upload_file
    blob = ActiveStorage::Blob.create_and_upload!(io: params[:file], filename: params[:file].original_filename)
    render json: { signedId: blob.signed_id }
  end

  def processed_tags
    params[:tag_names].split(",").map do |tag|
      Tag.find_or_initialize_by(name: tag.strip)
    end
  end

  def search
    if params[:search].present?
      @tickets = @project.tickets.search(params[:search])
    else
      @tickets = @project.tickets
    end

    render "projects/show"
  end

  private

  def ticket_params
    params.require(:ticket).permit(:name, :description, attachments: [])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def toggle_watching_button(ticket)
    text = if ticket.watchers.include?(current_user)
      "Unwatch"
    else
      "Watch"
    end
    link_to text, watch_project_ticket_path(ticket.project, ticket),
      class: text.parameterize, method: :patch
  end
end

app/views/tickets/_form.html.erb
<%= bootstrap_form_with(model: [project, ticket], local: true, label_errors: true) do |form| %>
  <%= form.text_field :name %>
  <%= form.text_area :description %>
  <% upload_url = upload_file_project_tickets_path(project) %>
  <div class="dropzone uploader mb-2" data-url="<%= upload_url %>"></div>

  <div class='form-group tags'>
    <div><%= label_tag :tag_names, "Tags" %></div>
    <%= render @ticket.tags, ticket: @ticket %>
    <%= text_field_tag :tag_names, "", class: "form-control" %>
  </div>

  <%= form.primary %>
<% end %>

app/views/tickets/_state_change.html.erb
<div class="state_change">
  <% if previous_state %>
    <strong><i class="fa fa-gear"></i> state changed</strong> from
    <%= render previous_state %> to <%= render new_state %>
  <% else %>
    <strong><i class="fa fa-gear"></i> state set</strong> to <%= render new_state %>
  <% end %>
</div>

app/views/tickets/edit.html.erb
<header>
  <h1>
    Edit Ticket
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/new.html.erb
<header>
  <h1>
    New Ticket
    <small><%= @project.name %></small>
  </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/show.html.erb
<div class="ticket">
  <header>
    <h1><%= @project.name %></h1>
  </header>

  <header>
    <h2><%= @ticket.name %></h2>

    <ul class="actions">
      <li><%= link_to "Edit Ticket", [:edit, @project, @ticket] %></li>
      <li><%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
  data: { confirm: "Are you sure you want to delete this ticket?"} %></li>
    </ul>
  </header>

  <table class="attributes">
    <tr>
      <th>Author:</th>
      <td><%= @ticket.author.email %></td>
    </tr>
    <tr>
      <th>Created:</th>
      <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
    </tr>
    <% if @ticket.state.present? %>
      <tr>
        <th>State:</th>
        <td><%= render @ticket.state %></td>
      </tr>
    <% end %>

    <% if @ticket.tags.any? %>
      <tr>
        <th>Tags:</th>
        <td class="tags"><%= render @ticket.tags, ticket: @ticket %></td>
      </tr>
    <% end %>

    <tr>
      <th>Watchers:</th>
      <td class="watchers">
        <%= toggle_watching_button(@ticket) %>
        <%= @ticket.watchers.map(&:email).to_sentence %>
      </td>
    </tr>
  </table>

  <%= simple_format(@ticket.description) %>

  <div class="comments">
    <header>
      <h3>Comments</h3>
    </header>

    <% comments = @ticket.comments.persisted.ordered %>
    <% if comments.any? %>
      <% state = nil %>
      <% comments.each do |comment| %>
        <%= render comment %>
        <% if comment.state != state %>
          <%= render "state_change", previous_state: state, new_state: comment.state %>
          <% state = comment.state %>
        <% end %>
      <% end %>

    <% else %>
      <p>There are no comments for this ticket.</p>
    <% end %>

    <%= render "comments/form", ticket: @ticket, comment: @comment %>
  </div>

  <% if @ticket.attachments.present? %>
    <h4>Attachment(s)</h4>
    <div class="attachments">
      <% @ticket.attachments.each do |attachment| %>
        <p>
          <%= link_to attachment.filename,
            rails_blob_path(attachment, disposition: 'attachment') %>
          (<%= number_to_human_size(attachment.blob.byte_size) %>)
        </p>
      <% end %>
    </div>
  <% end %>
</div>